import { FeedResponse, UserProfile, VideoItem } from '../types';

// Free publicly accessible MP4 videos (Google Cloud sample bucket)
export const MOCK_VIDEOS: VideoItem[] = [
  {
    id: 1,
    muxPlaybackId: null,
    webVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/2132180/pexels-photo-2132180.jpeg?auto=compress&cs=tinysrgb&w=800',
    place: 'Amalfi Coast',
    city: 'Salerno',
    country: 'Italy',
    category: 'Nature',
    viewCount: 42300,
    owner: { id: 1, username: 'marco_ventures', displayName: 'Marco Ventures', avatarUrl: null },
  },
  {
    id: 2,
    muxPlaybackId: null,
    webVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/1285625/pexels-photo-1285625.jpeg?auto=compress&cs=tinysrgb&w=800',
    place: 'Santorini',
    city: 'Thira',
    country: 'Greece',
    category: 'Architecture',
    viewCount: 87100,
    owner: { id: 2, username: 'elena.k', displayName: 'Elena K', avatarUrl: null },
  },
  {
    id: 3,
    muxPlaybackId: null,
    webVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=800',
    place: 'Kyoto Bamboo Forest',
    city: 'Kyoto',
    country: 'Japan',
    category: 'Nature',
    viewCount: 123400,
    owner: { id: 3, username: 'hiro.travels', displayName: 'Hiro Travels', avatarUrl: null },
  },
  {
    id: 4,
    muxPlaybackId: null,
    webVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/1320686/pexels-photo-1320686.jpeg?auto=compress&cs=tinysrgb&w=800',
    place: 'Patagonia',
    city: 'El Chaltén',
    country: 'Argentina',
    category: 'Adventure',
    viewCount: 56700,
    owner: { id: 4, username: 'sofia.wild', displayName: 'Sofia Wild', avatarUrl: null },
  },
  {
    id: 5,
    muxPlaybackId: null,
    webVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/2356045/pexels-photo-2356045.jpeg?auto=compress&cs=tinysrgb&w=800',
    place: 'Marrakech Medina',
    city: 'Marrakech',
    country: 'Morocco',
    category: 'Culture',
    viewCount: 34200,
    owner: { id: 5, username: 'amira.lens', displayName: 'Amira Lens', avatarUrl: null },
  },
  {
    id: 6,
    muxPlaybackId: null,
    webVideoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://images.pexels.com/photos/2422915/pexels-photo-2422915.jpeg?auto=compress&cs=tinysrgb&w=800',
    place: 'Bali Rice Terraces',
    city: 'Ubud',
    country: 'Indonesia',
    category: 'Nature',
    viewCount: 98500,
    owner: { id: 6, username: 'dewa.frames', displayName: 'Dewa Frames', avatarUrl: null },
  },
];

export const MOCK_FEED_RESPONSE: FeedResponse = {
  data: MOCK_VIDEOS,
  nextCursor: null,
};

export const MOCK_PROFILES: Record<number, UserProfile> = {
  1: {
    id: 1,
    username: 'marco_ventures',
    displayName: 'Marco Ventures',
    avatarUrl: null,
    videoCount: 24,
    followerCount: 4200,
    videos: MOCK_VIDEOS.filter((v) => v.owner.id === 1).map(({ owner, ...v }) => v),
  },
  2: {
    id: 2,
    username: 'elena.k',
    displayName: 'Elena K',
    avatarUrl: null,
    videoCount: 18,
    followerCount: 8700,
    videos: MOCK_VIDEOS.filter((v) => v.owner.id === 2).map(({ owner, ...v }) => v),
  },
  3: {
    id: 3,
    username: 'hiro.travels',
    displayName: 'Hiro Travels',
    avatarUrl: null,
    videoCount: 41,
    followerCount: 12300,
    videos: MOCK_VIDEOS.filter((v) => v.owner.id === 3).map(({ owner, ...v }) => v),
  },
  4: {
    id: 4,
    username: 'sofia.wild',
    displayName: 'Sofia Wild',
    avatarUrl: null,
    videoCount: 15,
    followerCount: 5600,
    videos: MOCK_VIDEOS.filter((v) => v.owner.id === 4).map(({ owner, ...v }) => v),
  },
  5: {
    id: 5,
    username: 'amira.lens',
    displayName: 'Amira Lens',
    avatarUrl: null,
    videoCount: 9,
    followerCount: 3400,
    videos: MOCK_VIDEOS.filter((v) => v.owner.id === 5).map(({ owner, ...v }) => v),
  },
  6: {
    id: 6,
    username: 'dewa.frames',
    displayName: 'Dewa Frames',
    avatarUrl: null,
    videoCount: 33,
    followerCount: 9800,
    videos: MOCK_VIDEOS.filter((v) => v.owner.id === 6).map(({ owner, ...v }) => v),
  },
};
